# Generated by Django 5.2.17 on 2026-10-01 11:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Заголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото'})})),
            ],
            options={
                'verbose_name': 'Текстовая страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Бренд', max_length=60, verbose_name='Название бренда')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='Короткое описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=60, verbose_name='Telegram (без @)')),
                ('instagram', models.CharField(blank=True, max_length=60, verbose_name='Instagram (без @)')),
                ('footer_note', models.CharField(blank=True, max_length=200, verbose_name='Текст в подвале')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
