# Generated by Django 5.2.17 on 2026-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='marquee',
            field=models.CharField(blank=True, help_text='Фразы через запятую, например: Доставка по РФ, Ручная работа. Пусто — без строки.', max_length=300, verbose_name='Бегущая строка'),
        ),
    ]
