# Generated by Django 5.2.17 on 2026-10-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('paid', 'Оплачена'), ('shipped', 'Отправлена'), ('cancelled', 'Отменена')], default='new', max_length=12, verbose_name='Статус')),
                ('product_title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена, ₽')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Размер')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('contact', models.CharField(max_length=120, verbose_name='Telegram / телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.productpage', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
