# Generated by Django 5.2.17 on 2026-10-04 16:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма, ₽'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_title',
            field=models.CharField(max_length=255, verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена за шт., ₽')),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productpage', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
